### ISSUE TITLE
Cannot traverse null values

### ISSUE THREAD

**Issue by thomashmolina** [leocavalcante/redact-sensitive#11]
In our PHP 8.3 servers, we encounter an issue where the RedactSensitiveProcessor attempts to traverse null values. We encounter the following exception:
```
"exception": {
            "class": "UnexpectedValueException",
            "message": "Don't know how to traverse value at key account_number",
            "code": 0,
            "file": "/var/www/vendor/leocavalcante/redact-sensitive/src/RedactSensitiveProcessor.php:84"
        }
```
A check should be added to see if the value is null. If it is, the key should be skipped, not traversed. Additionally, could we add a more specific error message? Like "Don't know how to traverse value of type {gettype($value)} at key $key"

**Comment by leocavalcante** [comment]
Fixed in #12, thanks @thomashmolina
